package com.yifan.lightning.deal.dao;

import com.yifan.lightning.deal.dataobject.NotificationDO;

import java.util.List;

public interface NotificationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jul 01 22:46:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jul 01 22:46:00 CST 2020
     */
    int insert(NotificationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jul 01 22:46:00 CST 2020
     */
    int insertSelective(NotificationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jul 01 22:46:00 CST 2020
     */
    NotificationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jul 01 22:46:00 CST 2020
     */
    int updateByPrimaryKeySelective(NotificationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Wed Jul 01 22:46:00 CST 2020
     */
    int updateByPrimaryKey(NotificationDO record);

    // list all notifications
    List<NotificationDO> listNotifications();

}