package com.yifan.lightning.deal.dao;

import com.yifan.lightning.deal.dataobject.UserItemDO;

import java.util.List;

public interface UserItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_item
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_item
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    int insert(UserItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_item
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    int insertSelective(UserItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_item
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    UserItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_item
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    int updateByPrimaryKeySelective(UserItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_item
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    int updateByPrimaryKey(UserItemDO record);

    // 根据用户id查询该用户购物车中的所有商品
    List<UserItemDO> listByUserId(Integer userId);

}