package com.yifan.lightning.deal.dataobject;

public class UserItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item.id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item.user_id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item.item_id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item.amount
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item.id
     *
     * @return the value of user_item.id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item.id
     *
     * @param id the value for user_item.id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item.user_id
     *
     * @return the value of user_item.user_id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item.user_id
     *
     * @param userId the value for user_item.user_id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item.item_id
     *
     * @return the value of user_item.item_id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item.item_id
     *
     * @param itemId the value for user_item.item_id
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item.amount
     *
     * @return the value of user_item.amount
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item.amount
     *
     * @param amount the value for user_item.amount
     *
     * @mbg.generated Sun Jun 28 00:00:19 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}